# theme
ZSH_THEME="spaceship"

# spaceship
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_RUBY_SYMBOL=' '
SPACESHIP_PYENV_SYMBOL=' '
SPACESHIP_ELIXIR_SYMBOL=' '
SPACESHIP_PACKAGE_SYMBOL=' '
SPACESHIP_NODE_SYMBOL=' '
SPACESHIP_EMBER_SYMBOL=' '
